<a href="https://colab.research.google.com/github/as9786/ML-DLPratice/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%EC%A4%80%EB%B9%84/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy ndarray

numpy의 핵심 기능 중 하나는 ndarray라고 하는 N차원의 배열 객체인데 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

In [2]:
a = np.array([1,2,3])
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


# List와 비교

In [3]:
l = [1,2,3]
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [4]:
a

array([1, 2, 3])

In [5]:
for item in l:
    print(item)

1
2
3


In [6]:
for item in a:
    print(item)

1
2
3


In [7]:
l.append(4)
l

[1, 2, 3, 4]

In [8]:
a = np.append(a,4)
a

array([1, 2, 3, 4])

In [9]:
l = l+[5]
l

[1, 2, 3, 4, 5]

In [10]:
#Broadcasting
a = a + np.array([5])
a

array([6, 7, 8, 9])

In [11]:
# list의 모든 원소를 2배로 만드기
l = [1,2,3]
l2 = []
for item in l:
    l2.append(item*2)
print(l2)

[2, 4, 6]


In [12]:
# ndarray의 모든 원소 2배 만들기
a = np.array(l)
a*2

array([2, 4, 6])

In [13]:
l*2

[1, 2, 3, 1, 2, 3]

# 배열

numpy 배열은 모두 같은 값의 유형이며, 음수가 아닌 정수의 튜플로 인덱싱됨. 차원의 수는 배열의 랭크. 배열의 shape는 각 차원별 배열 크기의 튜플, 중첩된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고 대괄호를 사용하여 요소에 접근할 수 있음

## 배열 생성하기

In [14]:
a = np.array([1,2,3])
print(a)
print(type(a),a.ndim,a.shape,a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


In [15]:
b = np.asarray(a) #얕은 복사
b 

array([1, 2, 3])

In [16]:
c = np.array(a)
c

array([1, 2, 3])

In [17]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [19]:
c[0] = 1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [20]:
a = np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [22]:
b = np.ones((5,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
c = np.full((2,3),4)
print(c)

[[4 4 4]
 [4 4 4]]


In [24]:
d = np.empty((3,3))
d

array([[3.93630242e-316, 1.77863633e-322, 0.00000000e+000],
       [0.00000000e+000, 4.34900600e+199, 1.00105331e+165],
       [1.16192989e+165, 6.56230677e-091, 8.60607447e-043]])

In [25]:
# like : 특정 배열의 모양 갖고오기
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a,2)
h = np.empty_like(a)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0.00000000e+000 0.00000000e+000 7.92975362e-321 2.89223381e-316]
 [6.91023292e-310 2.89223420e-316 6.91023292e-310 6.91023292e-310]
 [0.00000000e+000 2.47032823e-323 2.12199579e-314 5.43472210e-323]]


In [26]:
# 항등행렬
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
k = np.arange(10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# uniform distribution : 똑같은 확률로 뽑음
l = np.random.rand(2,2)
l

array([[0.68366905, 0.80448149],
       [0.53253662, 0.03839271]])

In [29]:
# normal distribution #표준정규분포
m = np.random.randn(2,2)
m

array([[ 2.54976534,  0.90257596],
       [ 0.67948512, -0.6947234 ]])

## 배열의 dtype

In [31]:
a = np.array([1,2,3])
b = np.array([1,2,3],dtype=np.float64)
c = np.array([1,2,3],dtype=np.int32)
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
int32


In [34]:
d = np.array([1,2,3],dtype='i1')
e = np.array([1,2,3],dtype='i2')
f = np.array([1,2,3],dtype='i4')
g = np.array([1,2,3],dtype='i8')
print(d.dtype,e.dtype,f.dtype,g.dtype)

int8 int16 int32 int64


In [35]:
d = np.array([1,2,3],dtype='u1')
e = np.array([1,2,3],dtype='u2')
f = np.array([1,2,3],dtype='u4')
g = np.array([1,2,3],dtype='u8')
print(d.dtype,e.dtype,f.dtype,g.dtype)

uint8 uint16 uint32 uint64


In [36]:
d = np.array([1,2,3],dtype='f2')
e = np.array([1,2,3],dtype='f4')
f = np.array([1,2,3],dtype='f8')
g = np.array([1,2,3],dtype='f16')
print(d.dtype,e.dtype,f.dtype,g.dtype)

float16 float32 float64 float128


In [37]:
#d = np.array([1,2,3],dtype='f2')
e = np.array([1,2,3],dtype='f')
f = np.array([1,2,3],dtype='d')
g = np.array([1,2,3],dtype='g')
print(e.dtype,f.dtype,g.dtype)

float32 float64 float128


In [38]:
e = e.astype(np.int32)
e.dtype

dtype('int32')

In [39]:
f = f.astype(e.dtype)
f.dtype

dtype('int32')

## 배열 indexing(색인)rhk slicing(슬라이싱)

### indexing, slicing 기본

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# indexing
a[5]

5

In [42]:
a[5:8]

array([5, 6, 7])

In [43]:
a[-1]

9

In [46]:
a[7:-1]

array([7, 8])

In [47]:
a[5:8] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

### indexing과 slicing 차이

indexing을 사용하면 항상 랭크가 감소. 반면에 slicing을 사용하면 차원이 유지

In [48]:
b = np.arange(1,13)
# b= b.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [49]:
indexing = b[1]
slicing = b[1:2]
print(indexing,indexing.shape,indexing.ndim)
print(slicing,slicing.shape,slicing.ndim)

2 () 0
[2] (1,) 1


In [50]:
b = b.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [52]:
row_r1 = b[1,:]
row_r2 = b[1:2,:]
print(row_r1,row_r1.shape,row_r1.ndim)
print(row_r2,row_r2.shape,row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


### slicing examples

In [53]:
c =np.arange(24).reshape(2,3,4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [54]:
print(c[:,:,:1])
print(c[...,:1]) # ... 앞의 전부 다를 의미

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [55]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


### boolean indexing

In [56]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
bool_idx = c>10
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [58]:
print(c[bool_idx]) # 차원을 무시하고 나옴

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [59]:
c[c>10]=-1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


### fancy indexing(정수 인덱싱)

In [60]:
d = np.arange(8).reshape(8,-1)
print(d,d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [61]:
d = np.hstack((d,d,d,d)) # 옆으로 붙이기
print(d,d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [62]:
print(d[[3,5,1,0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [63]:
print(d[[-3,-5,-7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [64]:
e = np.arange(32).reshape(8,4)
print(e,e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [65]:
print(e[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [70]:
print(e[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## Transpose

In [71]:
f = np.arange(16).reshape(2,2,4)
print(f,f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [72]:
print(f.transpose(1,0,2))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [74]:
print(f.swapaxes(0,1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


# Numpy 연산

In [77]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y= np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [78]:
print(x+y)
print(np.add(x,y)) #universal function

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [80]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [81]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [82]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [83]:
print(x@y)
print(np.matmul(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [84]:
z = np.arange(1,11).reshape(2,5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [85]:
print(np.sum(z))

55


In [86]:
sum1 = np.sum(z,axis=0)
sum2 = np.sum(z,axis=1)
sum3 = np.sum(z,axis=-1)
print(sum1,sum1.shape)
print(sum2,sum2.shape)
print(sum3,sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


여기서 축(axis)은 각 배열의 차원에 해당하는 index. axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소를 모두 더하라는 이야기. 

즉 위이 예에서 sum1의 경우 z[0:]+z[1:]의 연산을 하라는 의미이고,

sum2의 경우에는 z[:,0]+z[:,1]+...+z[:,4]를 하라는 의미

In [87]:
z[0,:]+z[1,:]

array([ 7,  9, 11, 13, 15])

In [88]:
z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4]

array([15, 40])

## Braodcasting

Broadcasting은 numpy가 산술 연산을 수행할 때 다른 모양의 배열로 작업할 수 있게 해주는 강력한 매커니즘. 종종 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러번 사용하여 더 큰 배열에서 어떤 연산을 수행하기 원할 때가 있음.

예를 들어, 행렬의 각 행에 상수 벡터를 추가하려 한다고 가정할 때, 다음과 같이 할 수 있음

In [89]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([[1,0,2]])

In [90]:
print(x,x.shape)
print(y,y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[1 0 2]] (1, 3)


In [91]:
z = x+y
z,z.shape

(array([[ 2,  2,  5],
        [ 5,  5,  8],
        [ 8,  8, 11],
        [11, 11, 14]]), (4, 3))

z = x+y는 broadcasting으로 인해 x가 (4,3)이고 yrk (3)인데도 작동. 이 행은 y가 실제로 (4,3)인 것처럼 작동. 각 행은 y의 사본이었고, 합계는 요소별로 수행

두 개의 배열을 브로드캐스팅하는 규칙은 다음을 따름

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙임
2. 두 배열은 차원의 크기가 같거나 배열 중 하나의 차원에 크기가 1인 경우 차원에서 호환가능
3. 배열은 모든 차원에서 호환되면 함께 broadcasting을 할 수 있음
4. Broadcast 후 각 배열은 두 개의 입력 배열 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사된 것처럼 작동


실제로 동작하는 방식

1. A와 B의 모양을 생각
2. 두 배열이 len(A.shape) == len(B.shape)인지 확인
3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1을 추가

- 예 : (5,3) -> (1,5,3)

4. shape가 1인 곳은 복사가 됨

- 예 : shape의 변화는 아래와 같음
- (5,3)+(3,)
- (5,3)+(1,3)
- (5,3)+(5,3)
- (5,3)

In [93]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([4,5]).reshape(1,2)
print(x,x.shape)
print(y,y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [94]:
x+y

ValueError: ignored

In [95]:
y = y.swapaxes(0,1)
y,y.shape

(array([[4],
        [5]]), (2, 1))

In [96]:
# Broadcasting 발생
x+y

array([[5, 6, 7],
       [6, 7, 8]])

# Shape 변경

In [97]:
a = np.arange(24).reshape(2,3,4)
a,a.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), (2, 3, 4))

In [98]:
a = a.reshape(4,-1)
a,a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), (4, 6))

In [99]:
a = a[...,np.newaxis]
a,a.shape

(array([[[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5]],
 
        [[ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]],
 
        [[12],
         [13],
         [14],
         [15],
         [16],
         [17]],
 
        [[18],
         [19],
         [20],
         [21],
         [22],
         [23]]]), (4, 6, 1))

In [103]:
a = a.reshape(4,6)
a = np.expand_dims(a,axis=1)
a,a.shape

(array([[[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]],
 
        [[18, 19, 20, 21, 22, 23]]]), (4, 1, 6))

In [104]:
b = a.copy()
b,b.shape

(array([[[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]],
 
        [[18, 19, 20, 21, 22, 23]]]), (4, 1, 6))

In [106]:
c = np.concatenate((a,b),axis=-1)
c,c.shape

(array([[[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17]],
 
        [[18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23]]]), (4, 1, 12))

In [107]:
c = np.concatenate((a,b),axis=0)
c,c.shape

(array([[[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]],
 
        [[18, 19, 20, 21, 22, 23]],
 
        [[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]],
 
        [[18, 19, 20, 21, 22, 23]]]), (8, 1, 6))

In [108]:
# stack은 차원을 늘림으로써 이어 붙임
d = np.stack((a,b),axis=-1)
d,d.shape

(array([[[[ 0,  0],
          [ 1,  1],
          [ 2,  2],
          [ 3,  3],
          [ 4,  4],
          [ 5,  5]]],
 
 
        [[[ 6,  6],
          [ 7,  7],
          [ 8,  8],
          [ 9,  9],
          [10, 10],
          [11, 11]]],
 
 
        [[[12, 12],
          [13, 13],
          [14, 14],
          [15, 15],
          [16, 16],
          [17, 17]]],
 
 
        [[[18, 18],
          [19, 19],
          [20, 20],
          [21, 21],
          [22, 22],
          [23, 23]]]]), (4, 1, 6, 2))

In [109]:
d = np.stack((a,b),axis=0)
d,d.shape

(array([[[[ 0,  1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10, 11]],
 
         [[12, 13, 14, 15, 16, 17]],
 
         [[18, 19, 20, 21, 22, 23]]],
 
 
        [[[ 0,  1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10, 11]],
 
         [[12, 13, 14, 15, 16, 17]],
 
         [[18, 19, 20, 21, 22, 23]]]]), (2, 4, 1, 6))