### numpy 호출

In [1]:
import numpy as np

### array 생성

In [10]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [3]:
a = np.array(a,int)
a

array([1, 2, 3, 4, 5])

In [4]:
test_array = np.array(['1','4',5.0,8],float)
test_array

array([1., 4., 5., 8.])

In [5]:
type(test_array)

numpy.ndarray

In [6]:
a is b

False

In [11]:
a[0] is b[-1]

True

In [12]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [13]:
test_array.dtype

dtype('float64')

In [15]:
a = [[1,2,3],[4,5,6],[4,5,6]]

In [17]:
np.array(a).shape

(3, 3)

### array shape

In [18]:
vector = [1,2,3,4]
np.array(vector,int).shape

(4,)

In [19]:
matrix = [[1,2,5,8],[1,2,5,8],[1,1,1,1]]
np.array(matrix,int).shape

(3, 4)

In [20]:
np.array(matrix,int).ndim

2

In [21]:
np.array(matrix,int).size

12

### numpy dtype

In [22]:
a = np.array([[1,2,3],[1,2,3]],dtype=np.int8)

In [23]:
a.dtype

dtype('int8')

In [24]:
a.nbytes

6

### reshape

In [25]:
test_matrix = [[1,2,3,4],[1,2,3,4]]

In [26]:
np.array(test_matrix).shape

(2, 4)

In [28]:
np.array(test_matrix).reshape(1,-1)

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [29]:
np.array(test_matrix).reshape(1,-1).shape

(1, 8)

### flat

In [30]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 3, 4])

# Indexing/Slicing

In [31]:
a = np.array([[1,2,3],[4.5,5,7]],int)
a

array([[1, 2, 3],
       [4, 5, 7]])

In [32]:
a[0][2]

3

In [33]:
a[0][0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  7]])

### slicing

In [34]:
a = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])
a

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [35]:
a[:,2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [36]:
a[:,1:3].shape

(4, 2)

In [37]:
a[1:2,:2] # 2-d

array([[1, 2]])

In [38]:
a[1]

array([1, 2, 5, 8])

In [39]:
a[1:2]

array([[1, 2, 5, 8]])

In [40]:
a = np.arange(100).reshape(10,10)

In [42]:
a[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

### arange

In [43]:
list(range(0,10,3))

[0, 3, 6, 9]

In [44]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### ones,zeros & empty

In [46]:
np.zeros(shape=(10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.ones(shape=(10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.empty(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [49]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### eye & identity & diag

In [50]:
np.identity(n=3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [51]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [52]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix,k=2)

array([2])

In [55]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### random

In [56]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.15554075, -0.7768895 , -1.95510863, -1.25887891, -0.52055377],
       [ 1.28395851,  0.95960073,  0.93938276,  0.61169489,  2.26844872]])

In [57]:
np.random.exponential(scale=2,size=100)

array([1.03468468, 1.47962086, 2.81420616, 1.0816676 , 1.77880189,
       0.9025232 , 2.03641592, 2.95301725, 1.44642935, 2.78856136,
       0.43201535, 1.70665053, 1.19117684, 2.85475852, 2.0805298 ,
       3.36503978, 1.13938795, 1.7563965 , 0.029591  , 1.42681952,
       0.06920351, 0.86336134, 2.40632975, 1.54926069, 1.88181874,
       2.80577581, 1.59716423, 2.68476083, 1.51193193, 0.40698559,
       1.00883255, 1.76962303, 1.01776288, 2.94478863, 0.5507232 ,
       6.03090952, 0.50765973, 1.21171501, 0.0153457 , 0.48905615,
       0.4843653 , 0.1943054 , 2.21432576, 0.75133484, 0.06514567,
       0.53806971, 2.36990283, 1.03753355, 1.42916505, 0.37862178,
       0.43910833, 0.46649787, 1.9092174 , 4.874077  , 8.21808658,
       0.77371347, 0.34442683, 1.49233545, 0.47430583, 1.75551328,
       3.23893844, 0.01605746, 0.63361206, 4.40638732, 0.30400288,
       0.43480775, 0.27947828, 1.1569434 , 3.21074947, 0.90163119,
       0.40986191, 1.33994665, 0.8458197 , 6.82997004, 0.14199

### operation

In [58]:
test_array = np.arange(1,11)

In [59]:
test_array.sum()

55

In [60]:
test_array.std()

2.8722813232690143

In [61]:
test_array = np.arange(1,13).reshape(3,4)

In [62]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
test_array.sum(1)

array([10, 26, 42])

In [64]:
test_array.sum(0)

array([15, 18, 21, 24])

In [65]:
t = np.array([test_array,test_array,test_array])
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [66]:
t.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [67]:
t.sum(1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [68]:
t.sum(0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [70]:
t.shape,t.sum(axis=2).shape

((3, 3, 4), (3, 3))

### concat

In [72]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [73]:
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [75]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [76]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [77]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = b[np.newaxis,:]
b

array([[5, 6]])

In [79]:
np.concatenate((a,b.T),1)

array([[1, 2, 5],
       [3, 4, 6]])

In [80]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [81]:
a+b

array([3, 5, 7])

In [82]:
a-b

array([-1, -1, -1])

In [84]:
a*b # element wise

array([ 2,  6, 12])

In [85]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [87]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [88]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### broadcasting

In [90]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [91]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [92]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [93]:
a //3

array([[0, 0, 1],
       [1, 1, 2]], dtype=int32)

In [94]:
a % 3

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [95]:
a = np.arange(1,13).reshape(4,3)
b = np.arange(10,40,10)
a + b

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### numpy performance

In [96]:
def scalar_vector_product(scalar,vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 1000000

vector = list(range(iternation_max))
scalar = 2

%timeit scalar_vector_product(scalar,vector)
%timeit [scalar * value for value in range(iternation_max)]
%timeit np.arange(iternation_max) * scalar

92.3 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
77.5 ms ± 2.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.76 ms ± 326 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
