In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.any(a>5)

True

In [4]:
np.any(a<0)

False

In [5]:
np.all(a>5)

False

In [6]:
np.all(a<10)

True

In [7]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [8]:
a = np.array([1,3,0])
b = np.array([5,2,1])

In [9]:
a > b

array([False,  True, False])

In [10]:
(a>b).any()

True

In [11]:
(a>b).all()

False

In [13]:
np.logical_and(a>0,a<3)

array([ True, False, False])

In [14]:
c = np.array([True,False,False])

In [15]:
np.logical_not(c)

array([False,  True,  True])

In [16]:
d = np.array([True,False,True])

In [18]:
np.logical_or(b,c)

array([ True,  True,  True])

In [19]:
a

array([1, 3, 0])

In [20]:
np.where(a>2)

(array([1], dtype=int64),)

In [21]:
np.where(a<3,3,2)

array([3, 2, 3])

In [23]:
a = np.array([1,np.NaN,np.inf])
a

array([ 1., nan, inf])

In [24]:
np.isnan(a)

array([False,  True, False])

In [25]:
np.isfinite(a)

array([ True, False, False])

### argmax&argmin

In [26]:
a = np.array([1,2,4,5,8,78,23,3])

In [27]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [28]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [31]:
np.argmax(a)

5

In [32]:
np.argmin(a)

0

In [33]:
a[np.argmin(a)]

1

In [34]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])

In [36]:
np.argmax(a,axis=1)

array([3, 1, 1], dtype=int64)

In [37]:
np.argmax(a,axis=0)

array([1, 1, 1, 1], dtype=int64)

### boolean index}

In [38]:
a = np.array([1,4,0,2,3,8,9,7])

In [39]:
a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [40]:
a[a>3]

array([4, 8, 9, 7])

In [42]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1],int) # 반드시 integer 

In [43]:
a[b]

array([2, 2, 4, 8, 6, 4])

In [44]:
a.take(b)

array([2, 2, 4, 8, 6, 4])

### fancy index

In [46]:
a = np.array([[1,4],[9,16]])
b = np.array((0,0,1,1,0))
c = np.array((0,1,1,1,1))

In [47]:
a[b,c]

array([ 1,  4, 16, 16,  4])

In [48]:
a[b]

array([[ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 1,  4]])

### loadtxt & savetxt

In [60]:
a_int = a.astype(int)
a_int[:3]

array([[ 1,  4],
       [ 9, 16]])

In [66]:
np.savetxt('int_data.csv',a_int,delimiter=', ',fmt='%d')#fmt='%.2e') #소수점 두 자리까지

In [68]:
a = np.loadtxt('int_data.csv',delimiter=', ')
a

array([[ 1.,  4.],
       [ 9., 16.]])

### numpy object-npy

In [69]:
np.save('npy_test_object',arr=a_int)

In [70]:
a_test = np.load('npy_test_object.npy')

In [72]:
a_test

array([[ 1,  4],
       [ 9, 16]])